stages:
  - build
  - deploy

# Build stage
build:
  image: node:16  # You can adjust the node version as needed
  stage: build
  script:
    - npm install     # Install dependencies
    - npm run build   # Build the production version of the app
  artifacts:
    paths:
      - build          # The build directory is the one created by React
    expire_in: 1 hour  # Optional: Make the artifacts expire after a certain time

# Deploy stage to GitLab Pages
pages:
  stage: deploy
  script:
    - mv build public  # Move the build folder to the public folder for GitLab Pages
  artifacts:
    paths:
      - public  # Make sure to deploy from the 'public' directory
  only:
    - main  # Only deploy on the 'main' branch, adjust if you use a different branch
